ALTER TABLE CLIENTE RENAME COLUMN CONTRASENA to CONTRASENIA;
ALTER TABLE FESTIVAL RENAME COLUMN AÑO to ANIO;
ALTER TABLE COMPAÑIAS_EN_FESTIVAL RENAME COLUMN ID_COMPAÑIA to ID_COMPANIA;

INSERT INTO USUARIO (ID,NOMBRE,MAIL,ROL) VALUES(1,'Nicolas','n.aguilar','Organizador');
INSERT INTO USUARIO (ID,NOMBRE,MAIL,ROL) VALUES(2,'Sarah','sd.solano','Administradora');
INSERT INTO USUARIO (ID,NOMBRE,MAIL,ROL) VALUES(3,'Camilo','caml','Musico');
INSERT INTO USUARIO (ID,NOMBRE,MAIL,ROL) VALUES(4,'Miguel','miguelMM','Financiero');
INSERT INTO USUARIO (ID,NOMBRE,MAIL,ROL) VALUES(5,'Daniela','d.jaimes','Ingeniera');
INSERT INTO USUARIO (ID,NOMBRE,MAIL,ROL) VALUES(6,'Sebastian','js.millan','Gerente');
INSERT INTO USUARIO (ID,NOMBRE,MAIL,ROL) VALUES(7,'Natalia','n.barreto','Secretaria');
INSERT INTO USUARIO (ID,NOMBRE,MAIL,ROL) VALUES(8,'Maria','mdr.leon','Profesora');
INSERT INTO USUARIO (ID,NOMBRE,MAIL,ROL) VALUES(9,'Fabiola','fabilejarde','Tesorera');
INSERT INTO USUARIO (ID,NOMBRE,MAIL,ROL) VALUES(10,'Daniel','dani.arbe','Vagabundo');
INSERT INTO USUARIO (ID,NOMBRE,MAIL,ROL) VALUES(11,'Valentina','valentable','Revisora fiscal');
INSERT INTO USUARIO (ID,NOMBRE,MAIL,ROL) VALUES(12,'Mauricio','mauro.vsc','Contratista');
INSERT INTO USUARIO (ID,NOMBRE,MAIL,ROL) VALUES(13,'David','davidal.v','Tecnico');

INSERT INTO ORGANIZADOR (ID) VALUES (1);
INSERT INTO ORGANIZADOR (ID) VALUES (2);
INSERT INTO ORGANIZADOR (ID) VALUES (6);
INSERT INTO ORGANIZADOR (ID) VALUES (11);
INSERT INTO ORGANIZADOR (ID) VALUES (13);

INSERT INTO CLIENTE (ID,ID_FESTIVAL,CONTRASENIA) VALUES (3,5,'0123');
INSERT INTO CLIENTE (ID,ID_FESTIVAL,CONTRASENIA) VALUES (8,1,'02119345');
INSERT INTO CLIENTE (ID,ID_FESTIVAL,CONTRASENIA) VALUES (3,2,'9934566');
INSERT INTO CLIENTE (ID,ID_FESTIVAL,CONTRASENIA) VALUES (4,5,'07829');
INSERT INTO CLIENTE (ID,ID_FESTIVAL,CONTRASENIA) VALUES (12,3,'9182');

INSERT INTO FESTIVAL (ID,ID_ORGANIZADOR,NAME,ANIO,PAIS,FECHAINICIO,FECHAFIN) VALUES(1,6,'Estereo Picnic',2017,'Colombia','27-03-2017','31-03-2017');
INSERT INTO FESTIVAL (ID,ID_ORGANIZADOR,NAME,ANIO,PAIS,FECHAINICIO,FECHAFIN) VALUES(2,11,'Festival de Samba',2010,'Brazil','02-01-2016','04-11-2016');
INSERT INTO FESTIVAL (ID,ID_ORGANIZADOR,NAME,ANIO,PAIS,FECHAINICIO,FECHAFIN) VALUES(6,1,'Rock al parque',2015,'Rusia','15-08-2010','20-12-2020');
INSERT INTO FESTIVAL (ID,ID_ORGANIZADOR,NAME,ANIO,PAIS,FECHAINICIO,FECHAFIN) VALUES(4,13,'Salsa festival',2011,'Barranquilla','17-04-1990','28-06-2005');
INSERT INTO FESTIVAL (ID,ID_ORGANIZADOR,NAME,ANIO,PAIS,FECHAINICIO,FECHAFIN) VALUES(5,2,'Baum festival',2003,'Argentina','25-07-2001','29-10-2030');

