EXPLAIN PLAN SET STATEMENT_ID = 'EX_RF11' FOR WITH COMPRADAS AS (SELECT * FROM (BOLETA INNER JOIN FUNCION ON ID_FUNCION = ID) WHERE ESTADO IN (1,2)),
     FILTRO_ELEMENTOS AS (SELECT * FROM (COMPRADAS C INNER JOIN REQUERIMIENTOS_SITIO RS ON C.ID_SITIO = RS.ID_SITIO )WHERE REQUERIMIENTOS = 'Telon desplegable'), --WHERE PARAMETRO
     FILTRO_LOCALIDAD AS (SELECT * FROM (FILTRO_ELEMENTOS FE INNER JOIN LOCALIDAD L ON FE.ID = L.ID ) WHERE NOMBRE='VIP' ), --WHERE PARAMETRO
     FILTRO_RANGO_FECHA AS (SELECT * FROM FILTRO_LOCALIDAD WHERE FECHA_HORA BETWEEN  '01/01/05' AND '01/01/19'),
     FILTRO_FRANJA_HORARIA AS (SELECT * FROM FILTRO_RANGO_FECHA where to_char(FECHA_HORA,'HH24') BETWEEN '1' AND '20'),
     FILTRO_DIA AS (SELECT * FROM FILTRO_FRANJA_HORARIA WHERE REPLACE(to_char(FECHA_HORA,'Day'), ' ', '') = 'Sábado'),
     UNION_SITIO AS (SELECT * FROM (FILTRO_DIA A INNER JOIN SITIO B ON A.ID_SITIO = B.ID)),
     NOMBRE_ESPECTACULO AS (SELECT * FROM(UNION_SITIO FD INNER JOIN (SELECT ID, NOMBRE AS NOMBRE_ESPECTACULO FROM ESPECTACULO) E ON  FD.ID_ESPECTACULO = E.ID)),
     BOLETAS_CONTADAS AS (SELECT * FROM (NOMBRE_ESPECTACULO NE INNER JOIN (SELECT ID_FUNCION AS FUNCION_ID ,COUNT(ID_FUNCION) AS BOLETAS_VENDIDAS FROM NOMBRE_ESPECTACULO GROUP BY ID_FUNCION)  A ON NE.ID_FUNCION = A.FUNCION_ID )),
     CLIENTES_CONTADOS AS (SELECT * FROM (BOLETAS_CONTADAS NE INNER JOIN (SELECT FUNCION_ID,COUNT(FUNCION_ID) AS CLIENTES_REGISTRADOS FROM BOLETAS_CONTADAS WHERE ID_CLIENTE != 99 GROUP BY FUNCION_ID) A ON NE.ID_FUNCION = A.FUNCION_ID ))
          
     SELECT DISTINCT ID_FUNCION, NOMBRE_ESPECTACULO, NOMBRE_SITIO,CAST(FECHA_HORA AS DATE) AS FECHA_FUNCION, BOLETAS_VENDIDAS, CLIENTES_REGISTRADOS FROM CLIENTES_CONTADOS;
     
     SELECT PLAN_TABLE_OUTPUT 
  FROM TABLE(DBMS_XPLAN.DISPLAY(NULL, 'EX_RF11', 'BASIC'));