--RF9
WITH LISTA_FUNCIONES AS (SELECT IDFUN FROM 
(SELECT ID AS IDFUN FROM FUNCION F INNER JOIN 
(SELECT ID AS IDESPECT FROM ESPECTACULO E INNER JOIN (
(SELECT CE.ID_ESPECTACULO FROM COMPANIA_ESPECTACULO CE WHERE CE.ID_COMPANIA = 1))
H ON E.ID=H.ID_ESPECTACULO) K ON F.ID_ESPECTACULO = K.IDESPECT)
INNER JOIN FUNCION ON IDFUN=ID WHERE FECHA_HORA BETWEEN '31/12/2000' AND '31/12/2029'),
ID_CLIENTES_FUN AS (SELECT DISTINCT ID_CLIENTE AS ID FROM LISTA_FUNCIONES LF 
INNER JOIN BOLETA B ON LF.IDFUN = B.ID_FUNCION)SELECT * FROM 
(SELECT * FROM ID_CLIENTES_FUN NATURAL JOIN CLIENTE) CL 
NATURAL JOIN USUARIO U WHERE ID !=99 AND 1=1 order by id;

--RF10
WITH LISTA_FUNCIONES AS (SELECT IDFUN FROM (SELECT ID AS IDFUN FROM FUNCION F 
INNER JOIN (SELECT ID AS IDESPECT FROM ESPECTACULO E INNER JOIN (
(SELECT CE.ID_ESPECTACULO FROM COMPANIA_ESPECTACULO CE WHERE CE.ID_COMPANIA = 1))
H ON E.ID=H.ID_ESPECTACULO)K ON F.ID_ESPECTACULO = K.IDESPECT) 
INNER JOIN FUNCION ON IDFUN=ID WHERE FECHA_HORA BETWEEN '31/12/2017' AND '31/12/2029'),
ID_CLIENTES_FUN AS (SELECT DISTINCT ID_CLIENTE AS ID FROM LISTA_FUNCIONES LF 
INNER JOIN BOLETA B ON LF.IDFUN = B.ID_FUNCION)SELECT * FROM 
(SELECT DISTINCT * FROM (SELECT ID FROM CLIENTE MINUS SELECT * FROM ID_CLIENTES_FUN))
NATURAL JOIN CLIENTE NATURAL JOIN USUARIO WHERE ID!=99 order by nombre;

SELECT PLAN_TABLE_OUTPUT 
  FROM TABLE(DBMS_XPLAN.DISPLAY(NULL, 'EX_RF9', 'BASIC'));
  
  SELECT PLAN_TABLE_OUTPUT 
  FROM TABLE(DBMS_XPLAN.DISPLAY(NULL, 'EX_RF10', 'BASIC'));
  
  select * from ALL_INDEXES;
  
 