
WITH LISTA_FUNCIONES AS (SELECT IDFUN FROM (SELECT ID AS IDFUN FROM FUNCION F INNER JOIN 
(SELECT ID AS IDESPECT FROM ESPECTACULO E INNER JOIN (
(SELECT CE.ID_ESPECTACULO FROM COMPANIA_ESPECTACULO CE WHERE CE.ID_COMPANIA = 2)) H ON E.ID=H.ID_ESPECTACULO)
K ON F.ID_ESPECTACULO = K.IDESPECT) INNER JOIN FUNCION ON IDFUN=ID WHERE FECHA_HORA BETWEEN '31/12/2017' AND '31/12/2029'),

ID_CLIENTES_FUN AS (SELECT DISTINCT ID_CLIENTE AS ID FROM LISTA_FUNCIONES LF INNER JOIN BOLETA B ON LF.IDFUN = B.ID_FUNCION)
SELECT * FROM (SELECT * FROM ID_CLIENTES_FUN NATURAL JOIN CLIENTE) CL NATURAL JOIN USUARIO U WHERE ID !=99 order by nombre;


WITH LISTA_FUNCIONES AS (SELECT IDFUN FROM (SELECT ID AS IDFUN FROM FUNCION F INNER JOIN 
(SELECT ID AS IDESPECT FROM ESPECTACULO E INNER JOIN (
(SELECT CE.ID_ESPECTACULO FROM COMPANIA_ESPECTACULO CE WHERE CE.ID_COMPANIA = 1)) H ON E.ID=H.ID_ESPECTACULO)
K ON F.ID_ESPECTACULO = K.IDESPECT) INNER JOIN FUNCION ON IDFUN=ID WHERE FECHA_HORA BETWEEN '31/12/2017' AND '31/12/2029'),

ID_CLIENTES_FUN AS (SELECT DISTINCT ID_CLIENTE AS ID FROM LISTA_FUNCIONES LF INNER JOIN BOLETA B ON LF.IDFUN = B.ID_FUNCION)
SELECT * FROM (SELECT DISTINCT * FROM (SELECT ID FROM CLIENTE MINUS SELECT * FROM ID_CLIENTES_FUN)) NATURAL JOIN CLIENTE NATURAL JOIN USUARIO WHERE ID!=99 order by nombre;

WITH COMPRADAS AS (SELECT * FROM (BOLETA INNER JOIN FUNCION ON ID_FUNCION = ID) WHERE ESTADO IN (1,2)),
     FILTRO_ELEMENTOS AS (SELECT * FROM (COMPRADAS C INNER JOIN REQUERIMIENTOS_SITIO RS ON C.ID_SITIO = RS.ID_SITIO )WHERE REQUERIMIENTOS = 'Telon desplegable'), --WHERE PARAMETRO
     FILTRO_LOCALIDAD AS (SELECT * FROM (FILTRO_ELEMENTOS FE INNER JOIN LOCALIDAD L ON FE.ID_LOCALIDAD = L.ID ) WHERE NOMBRE='Oro'), --WHERE PARAMETRO
     FILTRO_RANGO_FECHA AS (SELECT * FROM FILTRO_LOCALIDAD WHERE FECHA_HORA BETWEEN  '01/01/09 12:00:00,000000000 PM' AND '01/01/18 12:00:00,000000000 PM' )
      
select * FROM COMPRADAS;

SELECT * FROM FUNCION F WHERE F.FECHA_HORA BETWEEN '01/01/2018' AND '01/01/2030';

WITH LISTA_FUNCIONES AS (SELECT IDFUN FROM (SELECT ID AS IDFUN FROM FUNCION F INNER JOIN(SELECT ID AS IDESPECT FROM ESPECTACULO E inner join ((SELECT CE.ID_ESPECTACULO FROM COMPANIA_ESPECTACULO CE WHERE CE.ID_COMPANIA =2 )) H ON E.ID=H.ID_ESPECTACULO)K ON F.ID_ESPECTACULO = K.IDESPECT) INNER JOIN FUNCION ON IDFUN=ID WHERE FECHA_HORA BETWEEN '31/12/1999' AND '31/12/2029'),ID_CLIENTES_FUN AS (SELECT DISTINCT ID_CLIENTE AS ID FROM LISTA_FUNCIONES LF INNER JOIN BOLETA B ON LF.IDFUN = B.ID_FUNCION)SELECT * FROM (SELECT * FROM ID_CLIENTES_FUN NATURAL JOIN CLIENTE) CL NATURAL JOIN USUARIO U WHERE ID!=99 ORDER BY '' ;


WITH LISTA_FUNCIONES AS (SELECT IDFUN FROM (SELECT ID AS IDFUN FROM FUNCION F INNER JOIN
(SELECT ID AS IDESPECT FROM ESPECTACULO E inner join 
((SELECT CE.ID_ESPECTACULO FROM COMPANIA_ESPECTACULO CE WHERE CE.ID_COMPANIA =2 )) H ON E.ID=H.ID_ESPECTACULO)
K ON F.ID_ESPECTACULO = K.IDESPECT) 
INNER JOIN FUNCION ON IDFUN=ID WHERE FECHA_HORA BETWEEN '31/12/2014' AND '31/12/2029'),

ID_CLIENTES_FUN AS (SELECT DISTINCT ID_CLIENTE AS ID FROM LISTA_FUNCIONES LF INNER JOIN BOLETA B ON LF.IDFUN = B.ID_FUNCION)SELECT * FROM (SELECT * FROM ID_CLIENTES_FUN NATURAL JOIN CLIENTE) CL NATURAL JOIN USUARIO U;

